### PR TITLE
Fix : Dark-Mode-Issue #9

### LINKED ISSUE #9: Issue | Remove Dark mode TW classes
Dark mode is currently not configured and out of project scope at the moment. 
However, there are places where `dark:` Tailwind class is used in certain places.

In Tailwind, the `dark:[class]` is applied automatically if user's default theme in OS is set to dark.

Therefore, Remove all tailwind classes with prefix `dark:` so that all type of users see uniform styling.

Screenshot:
Screenshot 2024-04-27 at 7 56 44 AM

### PR DESCRIPTION
**Pull request by rahul-mahato29**
PR Fixes :  Removed all tailwind classes with prefix **dark:** so that all type of users can see uniform styling now.

Resolves #9 

 I have performed a self-review of my code, please check and let me know if anything requried from myside.

### CODE REVIEW

File: frontend/src/components/Appbar.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ const Appbar = () => {
           <Link to="/publish">
             <button
               type="button"
-              className="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 mx-12"
+              className="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2"
```
Comment (aadeshkulkarni) [inline frontend/src/components/Appbar.tsx:21]: Was `mx-12` removed intentionally ? If no, then please add it again.

Comment (rahul-mahato29) [reply frontend/src/components/Appbar.tsx]: Hey @aadeshkulkarni, 
added mx-12, please check it and confirm.
