### PR TITLE
Bugfix | Bookmarks | Route changed for logged in user

### LINKED ISSUE #153: Bug | Bookmarks page wrong navigation
In bookmarks page there is a text "No bookmarks yet! You can bookmark blogs in the blogs page [here](https://medium-app-zeta.vercel.app/signin)". where "here" is a link and on clicking it its navigating to signin page even we are logged in.
1.
Screenshot 2024-06-07 233858

### PR DESCRIPTION
**Pull request by AtharvaChobe**
fixes #153 

Uploading Recording 2024-06-12 142241.mp4…
image

### CODE REVIEW

File: frontend/src/components/BookmarkTab.tsx [hunk 1]
```diff
@@ -6,10 +6,15 @@ type BookmarkTabProps = {
   bookmarks: Post[];
 };
 const BookmarkTab = ({ bookmarks }: BookmarkTabProps) => {
+
+  const user = localStorage.getItem("user");
+
+
```
Comment (aadeshkulkarni) [inline frontend/src/components/BookmarkTab.tsx:12]: remove extra whitespaces

File: frontend/src/components/BookmarkTab.tsx [hunk 2]
```diff
@@ -6,10 +6,15 @@ type BookmarkTabProps = {
...
 const BookmarkTab = ({ bookmarks }: BookmarkTabProps) => {
+
+  const user = localStorage.getItem("user");
+
+  
   return (
     <div className="p-4 md:p-10 ">
       <h1 className="text-2xl font-bold mb-2">Bookmarks</h1>
       <div className="flex flex-col justify-center items-center bg-gray-50">
+
```
Comment (aadeshkulkarni) [inline frontend/src/components/BookmarkTab.tsx:17]: extra whitespace

File: frontend/src/components/BookmarkTab.tsx [hunk 3]
```diff
@@ -33,8 +39,21 @@ const BookmarkTab = ({ bookmarks }: BookmarkTabProps) => {
...
+        <div className="flex justify-center mt-10">
+          <h6 className="text-xl font-bold py-2">
+            No bookmarks yet! You can bookmark blogs in the blogs page{' '}
+            <Link to="/blogs" className="underline">
+              here
+            </Link>
+          </h6>
+        </div>
+      )}
+
```
Comment (aadeshkulkarni) [inline frontend/src/components/BookmarkTab.tsx:54]: This can be combined using optional chaining

```bash
{ (bookmarks.length === 0 && user) ?  (JSX for /blogs) : (JSX for /signin) }
```

File: frontend/src/components/BookmarkTab.tsx [hunk 4]
```diff
@@ -33,8 +39,21 @@ const BookmarkTab = ({ bookmarks }: BookmarkTabProps) => {
...
     </div>
   );
 };
 
-export default BookmarkTab;
+export default BookmarkTab;
```
Comment (aadeshkulkarni) [inline frontend/src/components/BookmarkTab.tsx:59]: remove extra whitespace

**Comment by AtharvaChobe** [comment]
just wanted to ask one thing , should i close this pull request and then create a new one or leave this as it is and create a new pull request

**Comment by aadeshkulkarni** [comment]
> just wanted to ask one thing , should i close this pull request and then create a new one or leave this as it is and create a new pull request

You should not need to create a new pull request.

You can make changes in your current branch, commit your code with changes, push it to the same branch. 
This PR will get automatically updated.

File: frontend/src/components/BookmarkTab.tsx [hunk 5]
```diff
@@ -23,18 +24,22 @@ const BookmarkTab = ({ bookmarks }: BookmarkTabProps) => {
...
+          <Link to="/blogs" className="underline">
+            here
+          </Link>
+        </h6>
+      </div>) : (<div className="flex justify-center mt-10">
+        <h6 className="text-xl font-bold py-2">
+          No bookmarks yet! You can bookmark blogs in the blogs page{' '}
+          <Link to="/signin" className="underline">
+            here
+          </Link>
```
Comment (aadeshkulkarni) [inline frontend/src/components/BookmarkTab.tsx:39]: Instead of repeating this code snippet twice in if else
```
<div className="flex justify-center mt-10">
        <h6 className="text-xl font-bold py-2">
          No bookmarks yet! You can bookmark blogs in the blogs page{' '}
          <Link to="/blogs" className="underline">
            here
          </Link>
        </h6>
      </div>
```
We can simply put the condition within like this

```bash
 <Link to={user? "/blogs" : "/signin"} ... />
 ```

Comment (AtharvaChobe) [reply frontend/src/components/BookmarkTab.tsx:39]: > Instead of repeating this code snippet twice in if else
> 
> ```
> <div className="flex justify-center mt-10">
>         <h6 className="text-xl font-bold py-2">
>           No bookmarks yet! You can bookmark blogs in the blogs page{' '}
>           <Link to="/blogs" className="underline">
>             here
>           </Link>
>         </h6>
>       </div>
> ```
> 
> We can simply put the condition within Link like this
> 
> ```shell
>  <Link to={user? "/blogs" : "/signin"} ... />
> ```

yes!
